# Generated by Django 3.1.6 on 2021-02-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_devices',
            fields=[
                ('d_ID', models.CharField(db_column='d_ID', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('d_see', models.IntegerField(db_column='d_see', default=1)),
                ('d_type', models.IntegerField(db_column='d_type')),
                ('d_sequence', models.IntegerField(db_column='d_sequence')),
                ('d_name', models.CharField(db_column='d_name', max_length=50)),
                ('d_date', models.DateField(db_column='d_date')),
                ('d_status', models.IntegerField(db_column='d_status', default=1)),
                ('d_place', models.CharField(db_column='d_place', max_length=50)),
                ('d_others', models.CharField(db_column='d_others', max_length=200, null=True)),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='All_users',
            fields=[
                ('u_ID', models.CharField(db_column='u_ID', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('u_name', models.CharField(db_column='u_name', max_length=15)),
                ('u_pass', models.CharField(db_column='u_pass', max_length=256)),
                ('u_auth', models.IntegerField(db_column='u_auth', default=1)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Borrow_return',
            fields=[
                ('b_ID', models.CharField(db_column='b_ID', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('b_date', models.DateField(db_column='b_date')),
                ('b_reason', models.CharField(db_column='b_reason', max_length=100)),
                ('b_place', models.CharField(db_column='b_place', max_length=50)),
                ('r_assign', models.DateField(db_column='r_assign', null=True)),
                ('r_date', models.DateField(db_column='r_date', null=True)),
                ('r_place', models.CharField(db_column='r_place', max_length=50, null=True)),
                ('b_device', models.ForeignKey(db_column='b_device', on_delete=django.db.models.deletion.CASCADE, to='app_database.all_devices')),
                ('b_user', models.ForeignKey(db_column='b_user', on_delete=django.db.models.deletion.CASCADE, to='app_database.all_users')),
            ],
            options={
                'db_table': 'borrow_return',
                'managed': True,
            },
        ),
    ]
