# Generated by Django 3.1.6 on 2021-02-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_devices',
            options={'managed': True, 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='all_users',
            options={'managed': True, 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='borrow_return',
            options={'managed': True, 'verbose_name_plural': 'borrow_return'},
        ),
        migrations.AddField(
            model_name='all_users',
            name='u_token',
            field=models.CharField(db_column='u_token', max_length=256, null=True),
        ),
    ]
