# Generated by Django 3.1.6 on 2021-02-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0002_auto_20210219_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_return',
            name='b_ID',
            field=models.CharField(db_column='b_ID', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
