# Generated by Django 3.1.6 on 2021-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0003_auto_20210223_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_return',
            name='b_date',
            field=models.DateTimeField(db_column='b_date'),
        ),
        migrations.AlterField(
            model_name='borrow_return',
            name='r_assign',
            field=models.DateTimeField(db_column='r_assign', null=True),
        ),
        migrations.AlterField(
            model_name='borrow_return',
            name='r_date',
            field=models.DateTimeField(db_column='r_date', null=True),
        ),
    ]
