# Generated by Django 3.1.6 on 2021-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0004_auto_20210223_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_return_view',
            fields=[
                ('b_ID', models.CharField(db_column='b_ID', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('b_name', models.CharField(db_column='b_name', max_length=15)),
                ('b_date', models.DateTimeField(db_column='b_date')),
                ('b_reason', models.CharField(db_column='b_reason', max_length=100)),
                ('b_place', models.CharField(db_column='b_place', max_length=50)),
                ('r_assign', models.DateTimeField(db_column='r_assign', null=True)),
                ('r_date', models.DateTimeField(db_column='r_date', null=True)),
                ('r_place', models.CharField(db_column='r_place', max_length=50, null=True)),
            ],
            options={
                'db_table': 'view_records',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='all_users',
            name='u_token',
        ),
    ]
