# Generated by Django 3.1.6 on 2021-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0005_auto_20210227_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_return_MyView',
            fields=[
                ('b_ID', models.CharField(db_column='b_ID', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('b_user', models.CharField(db_column='b_user', max_length=15)),
                ('b_device', models.CharField(db_column='b_device', max_length=12)),
                ('b_device_name', models.CharField(db_column='b_device_name', max_length=50)),
                ('b_date', models.DateTimeField(db_column='b_date')),
                ('b_reason', models.CharField(db_column='b_reason', max_length=100)),
                ('b_place', models.CharField(db_column='b_place', max_length=50)),
                ('r_assign', models.DateTimeField(db_column='r_assign', null=True)),
                ('r_date', models.DateTimeField(db_column='r_date', null=True)),
                ('r_place', models.CharField(db_column='r_place', max_length=50, null=True)),
            ],
            options={
                'db_table': 'view_myrecords',
                'managed': False,
            },
        ),
    ]
